config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :order_items
  resources :items
  resources :categories
  resource  :cart, only: %i[show update destroy]
  resources :orders
  resources :user_orders, only: %i[index update show]
  resources :admin, only: %i[index update]
  root 'items#index'

  get ':not_active_storage',
      to: 'application#route_not_found',
      constraints: { not_active_storage: %r{(?!rails/active_storage/blobs).*} }
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :set_cart
  before_action :set_cart_item, only: %i[update destroy]
  before_action :price_change
  before_action :show_line_total
  before_action :show_total
  after_action :destroy_empty_order, only: :destroy

  def show
    @all_items = @cart.order_items.includes(:item).cart_order unless @cart.nil?
  end

  def update
    if params[:increase]
      @cart_item.quantity += 1
    else
      @cart_item.quantity -= 1 unless @cart_item.quantity == 1
    end
    @cart_item.save
    show_line_total
    show_total
    respond_to do |format|
      format.html { redirect_to cart_path }
      format.js
    end
  end

  def destroy
    if @cart_item.destroy
      flash[:notice] = 'Item Removed from cart successfully'
      session[:cart_count] -= 1
    else
      flash[:alert] = 'Error Removing Item'
    end

    redirect_to cart_path
  end

  private

  def destroy_empty_order
    set_cart
    session[:cart_count] = 0
    @cart.destroy if @cart.order_items.blank?
  end

  def cart_params
    params.permit(:item_id)
  end

  def set_cart
    @cart = Order.find_by(id: session[:order_id], status: :in_progress) unless Order.find_by(id: session[:order_id], status: :in_progress).nil?
  end

  def show_line_total
    calculate_line_total unless @cart&.order_items.nil?
  end

  def calculate_line_total
    ActiveRecord::Base.transaction do
      if @cart_item.nil?
        @cart.order_items.each do |item|
          item.total = item.unit_price * item.quantity
          item.save
        end
        @cart.save
      else
        @cart_item.total = @cart_item.unit_price * @cart_item.quantity
        @cart_item.save
      end
    end
  end

  def show_total
    calculate_total unless @cart.nil?
  end

  def calculate_total
    ActiveRecord::Base.transaction do
      @cart.total = @cart.order_items.includes([:item]).map(&:total).inject(:+) unless @cart.nil?
      save_cart
    end
  end

  def save_cart
    @cart.save
  end

  def price_change
    price_change_helper if @cart.present?
  end

  def price_change_helper
    ActiveRecord::Base.transaction do
      @cart.order_items.includes([:item]).each do |order_item|
        order_item.unit_price = order_item.item.price if order_item.unit_price != order_item.item.price
        order_item.save
      end
    end
  end

  def set_cart_item
    @cart_item = @cart.order_items.find_by(cart_params)
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/show.html.erb
<h1>Shopping Cart</h1>
<%if @cart.nil? %>
  <h2>Cart is Empty</h2>
<% else %>
  <table class='table'>
    <tr>
      <th colspan='1'>
      <th>Title</th>
      <th>Unit Price</th>
      <th colspan='1'></th>
      <th>Count</th>
      <th colspan='1'></th>
      <th>Line_item total</th>
      <th colspan='2'></th>
    </tr>
      <%= render @all_items %>
    <tr>
      <td colspan='4'></td>
      <td>Total</td>
      <td id='cart_total'><%= @cart.total %></td>
    </tr>
    <tr>
      <td colspan='5'></td>
      <td><%= link_to 'Checkout',user_order_path(id: @cart , status: :paid), method: :patch, class: 'btn btn-dark' %></td>
    </tr>
  </table>
<%end%>

app/views/carts/update.js.erb
$(`#quantity-${'<%= @cart_item.item_id %>'}`).html('<%= @cart_item.quantity %>');
$(`#item_total-${'<%= @cart_item.item_id %>'}`).html('<%= @cart_item.total %>');
$(`#cart_total`).html('<%= @cart.total %>')