config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :order_items
  resources :items
  resources :categories
  resource  :cart, only: %i[show update destroy]
  resources :orders
  resources :user_orders, only: %i[index update show]
  resources :admin, only: %i[index update]
  root 'items#index'

  get ':not_active_storage',
      to: 'application#route_not_found',
      constraints: { not_active_storage: %r{(?!rails/active_storage/blobs).*} }
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  has_one_attached :picture
  has_and_belongs_to_many :categories, dependent: :nullify
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

  enum status: { active: 0, retired: 1 }

  accepts_nested_attributes_for :categories

  validates :picture, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  validates :title, presence: true, allow_blank: false
  validates :title, uniqueness: { case_sensitive: false }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :price, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }
  validates :description, presence: true, allow_blank: false
  validates :categories, presence: true

  scope :sorted_by_title, -> { order('items.title ASC') }

  before_create :set_default_image

  def set_default_image
    attach_image if picture.attachment.nil?
  end

  def attach_image
    picture.attach(io: File.open(Rails.root.join('app/assets/images/cookie.jpeg').to_s), filename: 'cookie.jpeg', content_type: 'image/jpeg')
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = if params[:q]
               Item.search(params[:q]).result
             else
               Item.includes(%i[items_categories categories]).with_attached_picture.sorted_by_title
             end.page(params[:page]).per(5)
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    authorize @item
    if @item.save
      flash[:notice] = 'Item Created Successfully'
      (redirect_to items_path)
    else
      render 'new'
    end
  end

  def edit
    authorize item
  end

  def update
    authorize item
    if @item.update(item_params)
      flash[:notice] = 'Item Updated Successfully'
      (redirect_to @item)
    else
      render 'edit'
    end
  end

  def show
    item
  end

  def destroy
    authorize item
    flash[:alert] = if @item.destroy
                      'Item Removed'
                    else
                      'Item Could Not Be Removed'
                    end
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :price, :picture, :status, :q, category_ids: [])
  end

  def item
    @item ||= Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item, local: true  do |form|%>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %> prohibited
        this item from being saved:
      </h2>
      <ul>
        <% @item.errors.each do |attr,msg| %>
          <li><%= attr %> <%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='mb3'>
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, required: true, class:'form-control' %>
  </div>
  <br>
  <div class='mb3'>
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_field :description,required: true, class: 'form-control' %>
  </div>
  <br>
  <div class='mb3'>
    <%= form.label :price, class: 'form-label' %>
    <%= form.number_field :price, step: :any, class: 'form-control',required: true, placeholder: 'e.g 2.99' %>
  </div>
  <br>
  <div class='mb3'>
    <%= form.label :category %>
    <br>
    <div class='form-check'>
    <%= form.collection_check_boxes :category_ids, Category.order(:category).all, :id, :category, class: 'form-check-input' %>
    </div>
  </div>
  <br>
  <div class='mb3'>
    <%= form.file_field :picture %>
  </div>
  <br>
  <%if @item.id.present? %>
  <div class='mb3'>
     <%= cl_image_tag(@item.picture.key, height: 100, width: 100, gravity: :face, crop: :thumb, sign_url: true, default_image: 'cookie.jpeg') %>
  </div>
  <br>
  <div class='mb3'>
      <%=form.submit 'Update Item', data: { disable_with: 'Saving...' }, class: 'btn btn-primary' %>
  </div>
  <% else %>
    <div class='mb3'>
    <%= form.submit 'Add Item', data: { disable_with: 'Saving...' }, class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

app/views/items/_search_form.html.erb
<div class='d-flex'>
  <form class='pt-2'>
    <%= search_form_for(@q,url: items_path, method: :get)  do |f| %>
      <%= f.search_field :title_cont, placeholder: 'Search Product' %>
      <%= f.submit %>
    <% end %>
  </form>
</div>

app/views/items/edit.html.erb
<h1>Edit Item</h1>
<%= render 'form' %>
<%= link_to 'Back',url_for(:back), class: 'btn btn-dark' %>

app/views/items/index.html.erb
<%= render 'search_form' %>
<%unless @items.exists? %>
  <h2>No Items Found</h2>
<% else %>
  <table class='table'>
    <tr>
      <th colspan='1'>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <th colspan='4'></th>
    </tr>
    <% @items.each do |item| %>
      <tr>
        <td><%= cl_image_tag(item.picture.key, height: 100, width: 100, gravity: :face, crop: :thumb, sign_url: true) %></td>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td><%= render item.categories %></td>
        <td><%= link_to 'Show Item',item_path(item), class: 'btn btn-dark' %></td>
        <%if item.active? %>
          <td><%= link_to 'Add to Cart',order_items_path(item_id: item.id, unit_price: item.price, item_title: item.title), method: :post, remote: true,class: 'btn btn-dark' %></td>
        <% end %>
        <% if current_or_guest_user.admin? %>
          <td><%= link_to 'Edit Item',edit_item_path(item),class: 'btn btn-dark' %></td>
          <% if item.active? %>
            <td><%= link_to 'Retire Item', item_path(id: item.id, item: { status: :retired }),method: :patch, class: 'btn btn-dark' %></td>
          <% else %>
            <td><%= link_to 'Activate Item', item_path(id: item.id, item: {status: :active }),method: :patch, class: 'btn btn-dark' %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= paginate @items %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>
<%= render 'form' %>
<br>
<%= link_to 'Back',url_for(:back), class: 'btn btn-dark' %>

app/views/items/show.html.erb
<%= cl_image_tag(@item.picture.key, height: 100, width: 100, gravity: :face, crop: :thumb, sign_url: true, default_image: 'cookie.jpeg') %>

<h4 class= 'display-4'><%= @item.title %></h4>
<br>
<p class ='display-6'><%= @item.description %></p>
<br>
<p class ='h3'>Price: <%= @item.price %></p>
<br>
<p class ='display-6'><%= @item.status %></p>
<br>
<% if @item.active? %>
  <%= link_to 'Add to Cart',order_items_path(item_id: @item.id, unit_price: @item.price, item_title: @item.title),remote: true, method: :post,class: 'btn btn-dark' %>
<% end %>
<%= link_to 'Back', url_for(:back), class:'btn btn-dark' %>