config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :order_items
  resources :items
  resources :categories
  resource  :cart, only: %i[show update destroy]
  resources :orders
  resources :user_orders, only: %i[index update show]
  resources :admin, only: %i[index update]
  root 'items#index'

  get ':not_active_storage',
      to: 'application#route_not_found',
      constraints: { not_active_storage: %r{(?!rails/active_storage/blobs).*} }
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_and_belongs_to_many :items, dependent: :nullify

  validates :category, presence: true
  validates :category, uniqueness: { case_sensitive: false }
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    authorize @category
  end

  def show
    @category_items = category.items.includes(%i[items_categories categories]).with_attached_picture.sorted_by_title
  end

  def create
    @category = Category.new(category_params)
    authorize @category
    if @category.save
      flash[:notice] = 'Category Created'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def destroy
    authorize category
    if @category.destroy
      flash[:notice] = 'Category Removed'
    else
      flash[:alert] = 'Category Could Not Be Removed'
    end
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:id, :category)
  end

  def category
    @category ||= Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_category.html.erb
<%= category.category %>
<br>

app/views/categories/_form.html.erb
<%= form_with model: @category, local: true  do |form| %>
  <% if @category.errors.any? %>
    <div id='error_explanation'>
      <h2>
        <%= pluralize(@category.errors.count, 'error') %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='mb3'>
    <%= form.label :category, class: 'form-label' %>
    <%= form.text_field :category, class:'form-control', required: true %>
  </div>
  <br>
  <div class='mb3'>
    <%= form.submit 'Add Category', data: { disable_with: 'Saving...' }, class: 'btn btn-primary' %>
  </div>
<%end%>

app/views/categories/index.html.erb
<%if current_or_guest_user.admin?%>
  <%= link_to 'New Category',new_category_path, class: 'btn btn-dark' %>
<%end%>
<table class='table'>
  <tr>
    <th>Category</th>
    <th colspace='1'></th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.category %></td>
      <td><%= link_to 'Show Items',category_path(category), class: 'btn btn-dark' %>
      <%if current_or_guest_user.admin? %>
        <td><%= link_to 'Destroy', category_path(category),
              method: :delete,
              data: { confirm: 'Are you sure?' },class: 'btn btn-dark' %></td>
      <%end%>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render 'form' %>
<br>
<%= link_to 'Back',url_for(:back), class: 'btn btn-dark' %>

app/views/categories/show.html.erb
<% if @category.nil? %>
  <h1>No Items in this Category</h1>
<% else %>
  <h2>Category: <%= @category.category%></h2>
  <table class='table'>
    <tr>
      <th colspan='1'>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan='1'></th>
    </tr>
    <% @category_items.each do |item| %>
    <tr>
      <td><%= cl_image_tag(item.picture.key, height: 100, width: 100, gravity: :face, crop: :thumb, sign_url: true) %></td>
      <td><%= item.title %></td>
      <td><%= item.description %></td>
      <td><%= item.price %></td>
      <% if item.active? %>
        <td><%= link_to 'Add to Cart',order_items_path(item_id: item.id, unit_price: item.price, item_title: item.title),remote: true, method: :post,class: 'btn btn-dark' %></td>
      <% end %>
      <td><%= link_to 'Show Item',item_path(item), class: 'btn btn-dark' %></td>
    </tr>
    <% end %>
  </table>
  <td><%= link_to 'Back',url_for(:back), class: 'btn btn-dark' %></td>
<% end %>