config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :order_items
  resources :items
  resources :categories
  resource  :cart, only: %i[show update destroy]
  resources :orders
  resources :user_orders, only: %i[index update show]
  resources :admin, only: %i[index update]
  root 'items#index'

  get ':not_active_storage',
      to: 'application#route_not_found',
      constraints: { not_active_storage: %r{(?!rails/active_storage/blobs).*} }
end

app/views/layouts/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
  <div class='container-fluid'>
    <%= link_to 'Dinner Dash',items_path, class:'navbar-brand' %>
    <button class='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>
    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav me-auto mb-2 mb-lg-0'>
        <li class='nav-item'>
          <%= link_to 'Home',items_path, class:'nav-link' %>
        </li>
        <% if current_user&.admin? %>
          <li class='nav-item'>
            <%= link_to 'New Item',new_item_path, class:'nav-link' %>
          </li>
        <% end %>
        <li class='nav-item'>
          <%= link_to 'Categories',categories_path, class:'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to 'My Cart', cart_path, class:'nav-link' %>
        </li>
        <li class='nav-item'>
          <div class= 'nav-link' id='cart'><%= session[:cart_count] %></div>
        </li>
        <% if user_signed_in?%>
          <% if current_user.admin? %>
            <li class='nav-item'>
              <%= link_to 'All Orders', orders_path, class:'nav-link' %>
            </li>
            <li class='nav-item'>
              <%= link_to 'All Users', admin_index_path, class:'nav-link' %>
            </li>
          <% else %>
            <li class='nav-item'>
              <%= link_to 'My Orders', user_orders_path, class:'nav-link' %>
            </li>
          <% end %>
          <li class='nav-item'>
            <%= link_to 'Edit Profile', edit_user_registration_path(current_user), class:'nav-link' %>
          </li>
          <li class='nav-item'>
            <%= link_to 'Sign out',destroy_user_session_path, method: :delete, class:'nav-link' %>
          </li>
        <% else %>
          <li class='nav-item'>
            <%= link_to 'Sign up',new_user_registration_path, class:'nav-link' %>
          </li>
          <li class='nav-item'>
            <%= link_to 'Sign in',new_user_session_path, class:'nav-link' %>
          </li>
        <% end %>
      </ul>
      <div class='d-flex'>
        <h4 class='navbar-text px-4'><%= current_user.display_name if user_signed_in? %></h4>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang='en'>
  <head>
    <!-- Required meta tags -->
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <!-- Bootstrap CSS -->
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU' crossorigin='anonymous'>

    <title>DinnerDash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div id='flash'>
      <%= render 'shared/notice' %>
    </div>
    <div class = 'container'>
      <br>
      <%= yield %>
    </div>
    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js' integrity='sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ' crossorigin='anonymous'></script>
  </body>
</html>